version: '3.9'

services:

  postgres-server:
    name: 'caterin-postgres-server'
    image: postgres
    restart: always
    volumes:
      - ${SQL_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  ldap-server:
    name: 'catering-ldap-server'
    image: thoteam/slapd-server-mock
    restart: always
    volumes:
      - ${LDAP_CONFIG_PATH}:/bootstrap
    ports:
      - 389:389

  seoulair-device:
        container_name: seoulair-device
        restart: always
        image: seoulair-device
        network_mode: bridge
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 5500:5500
        links:
            - sql-server
            - ldap-server