version: '3.9'

services:

  postgres-server:
    container_name: 'catering-postgres-server'
    image: postgres
    restart: always
    volumes:
      - ${SQL_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  ldap-server:
    container_name: 'catering-ldap-server'
    image: thoteam/slapd-server-mock
    restart: always
    volumes:
      - ${LDAP_CONFIG_PATH}:/bootstrap
    ports:
      - 389:389

  catering-api:
    container_name: catering-api
    restart: always
    image: catering-api
    network_mode: bridge
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - 5500:5500
    links:
      - postgres-server
      - ldap-server
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'