version: '3.9'

services:

  postgres-server:
    image: postgres
    restart: always
    volumes:
      - ${SQL_DATA_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    profiles:
      - 'persistance'
      - 'catering-api'

  postgres-portal:
    image: dpage/pgadmin4
    restart: on-failure
    ports: 
      - 5550:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"

  ldap-server:
    image: thoteam/slapd-server-mock
    restart: always
    volumes:
      - ${LDAP_CONFIG_PATH}:/bootstrap
    profiles:
      - 'catering-api'

  catering-api:
    restart: always
    image: catering-api
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MAIN_PORT: 5500
    ports:
      - 5500:5500
    environment:
      ASPNETCORE_ENVIRONMENT: 'Container'
    profiles:
      - 'catering-api'