// <auto-generated />
using System;
using Catering.Infrastructure.Mailing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catering.Infrastructure.Mailing.Migrations
{
    [DbContext(typeof(MailingDbContext))]
    partial class MailingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mailing")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catering.Application.Mailing.Emails.EmailTemplate", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("HtmlTemplate")
                        .HasColumnType("text")
                        .HasColumnName("html_template");

                    b.HasKey("Name")
                        .HasName("pk_templates");

                    b.ToTable("templates", "mailing");
                });

            modelBuilder.Entity("Catering.Application.Mailing.Emails.FailedCateringEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_on");

                    b.Property<string>("Recepiants")
                        .HasColumnType("text")
                        .HasColumnName("recepiants");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_failed_emails");

                    b.ToTable("failed_emails", "mailing");
                });
#pragma warning restore 612, 618
        }
    }
}
